CREATE DATABASE LMS
USER LMS
GO
CREATE TABLE Professor
(
ID SMALLINT (100,1) NOT NULL,
APELIDO VARCHAR (20) NOT NULL,
EMAIL VARCHAR (25) NOT NULL,
CELULAR TINYINT (20) NOT NULL,
CONSTRAINT PKID PRIMARY KEY (ID),
CONSTRAINT UQEMAIL UNIQUE (EMAIL),
CONSTRAINT UQCELULAR UNIQUE(CELULAR)
);


CREATE TABLE Usuario
(
LOGIN VARCHAR (20) NOT NULL,
SENHA TINYINT (20) NOT NULL,
DT EXPIRACAO DATE CONSTRAINT DTEXP DEFAULT 01/01/1990 NOT NULL ,
CONSTRAINT UQLOGIN UNIQUE (LOGIN)
);


CREATE TABLE Coordenador
(
ID SMALLINT IDENTITY NOT NULL,
ID_USUARIO VARCHAR (30)NOT NULL,
NOME VARCHAR (50) NOT NULL,
EMAIL VARCHAR (25) NOT NULL,
CELULAR TINYINT (20) NOT NULL,
CONSTRAINT PKID PRIMARY KEY (ID),
CONSTRAINT UQEMAIL UNIQUE (EMAIL),
CONSTRAINT UQCELULAR UNIQUE(CELULAR),
);


CREATE TABLE DisciplinaOfertada(
ID SMALLINT IDENTITY NOT NULL ,
IdCoordenador SMALLINT NOT NULL,
DtInicioMatricula DATE NULL,
DtFimMatricula DATE NULL,
IdDisciplina TINYINT NOT NULL,
IdCurso TINYINT NOT NOT NULL,
Ano DATE NOT NULL,
Semestre TINYINT NOT NULL,
Turma CHAR(1) NOT NOT,
IdProfessor TINYINT NOT NULL,
Metodologia VARCHAR(50) NULL,
Recursos VARCHAR(30) NULL,
CriterioAvaliacao VARCHAR(30) NULL,
PlanoDeAulas VARCHAR(50) NULL,
CONSTRAINT pkDisciplinaOfertada PRIMARY KEY (ID),
CONSTRAINT fkCoordenador FOREIGN KEY (IdCoordenador) REFERENCES Coordenador(ID),
CONSTRAINT fkDisciplina FOREIGN KEY (IdDisciplina) REFERENCES Disciplina(ID),
CONSTRAINT fkCurso FOREIGN KEY (IdCurso) REFERENCES Curso(ID),
CONSTRAINT fkProfessor FOREIGN KEY (IdProfessor) REFERENCES Professor(ID),
CONSTRAINT ckAno CHECK (Ano BETWEEN 1900 AND 2100)
CONSTRAINT ckSemestre CHECK (Semestre BETWEEN 1 AND 2)
CONSTRAINT ckTurma CHECK (Turma LIKE [A-Z])
);

CREATE TABLE Curso(
    ID TINYINT IDENTITY,
    Nome VARCHAR(50) NOT NULL,
    CONSTRAINT pkCurso PRIMARY KEY (ID),
    CONSTRAINT ukNome UNIQUE KEY (Nome)
);

CREATE TABLE AtividadeVinculada(
    ID SMALLINT IDENTITY,
    IdAtividade SMALLINT,
    IdProfessor SMALLINT,
    IdDisciplinaOfertada SMALLINT,
    Rotulo CHAR(4) NOT NULL,
    Status VARCHAR(20) NOT NULL,
    DtInicioResposta DATE NOT NULL,
    DtFimResposta DATE NOT NULL, 
    CONSTRAINT pkAtividadeVinculada PRIMARY KEY(ID),
    CONSTRAINT fkProfessor FOREIGN KEY (IdProfessor) REFERENCES Professor(ID),
    CONSTRAINT fkAtividade FOREIGN KEY (IdAtivida) REFERENCES Atividade(ID),
    CONSTRAINT fkDisciplinaOfertada FOREIGN KEY (IdDisciplinaOfertada) 
    REFERENCES DisciplinaOfertada(ID),

);
